#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh --material
xrandr --output DisplayPort-0 --primary --mode 2560x1080 --output HDMI-A-0 --mode 1920x1080 --below DisplayPort-0 --output DisplayPort-1 --mode 1600x900 --right-of HDMI-A-0 &
tablet.sh &
redshift -P -O 4000 &
nitrogen --restore &
picom &
xsetroot -cursor_name left_ptr &
nm-applet &
flameshot &
corectrl &
blueman-applet &
pasystray &
echo hook:module/ipc1 >>/tmp/polybar_mqueue.* &
polybar-spotify-listener.py &


bspc monitor -d I II III IV V VI VII VIII IX X

bspc monitor DisplayPort-0 -d I II III IV
bspc monitor HDMI-A-0 -d V VI VII
bspc monitor DisplayPort-1 -d VIII IX X

bspc config border_width         3
bspc config window_gap          12
bspc config focused_border_color "#FFFFFF"
bspc config normal_border_color "#5E81AC"
bspc config active_border_color "#FE81AC"

bspc config pointer_follows_focus false
bspc config focus_follows_pointer true
bspc config ignore_ewmh_fullscreen all

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^1'
#bspc rule -a Spotify desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a nautilus state=floating follow=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey mange=off
bspc rule -a Emacs state=tiled
bspc rule -a looking-glass-client state=fullscreen

bspc rule -a scratchpad sticky=on state=floating hidden=on
# check scratchpad already running
#
